### ISSUE TITLE
Quickbooks 3100 and 500 internal server error for sandbox

### ISSUE THREAD

**Issue by golevel** [activecollab/quickbooks#3]
Hi there,

We're giving this repo a try and we can't seem to get it to work. We tried the $dataService method to select customer data, but we keep getting a 3100 error and a 500 internal server error. 

We found this post here:

https://intuitdeveloper.lc.intuit.com/questions/1335951-getting-a-3100-errorcode-and-500-internal-server-error-on-any-request

That seems to indicate that the client secret needs to be url encoded, which we tried but we still get the same error. Any help would be greatly appreciated.

**Comment by petarslavnic** [comment]
Please use ActiveCollab\Quickbooks\Sandbox. Sandbox extends ActiveCollab\Quickbooks\DataService but with sandbox api url.

**Comment by golevel** [comment]
Thanks, that did the trick.
