### ISSUE TITLE
Guzzle not found

### ISSUE THREAD

**Issue by PsychicCat** [activecollab/quickbooks#5]
It looks like the recent updates of league/oauth1-client's Guzzle dependency breaks the DataService because Guzzle is now in a different namespace. Seems to be some other breaking changes in Guzzle as well...looking into it

```
  "message": "Class 'Guzzle\\Service\\Client' not found",
  "code": 1,
  "status_code": 500,
  "debug": {
    "line": 68,
```

**Comment by petarslavnic** [comment]
Yep, BC broken in Sem Ver. Will give my best to fix this quickly.

**Comment by PsychicCat** [comment]
Thanks! I tracked it down to the request method in DataService, new version of guzzle has different params.

something like this might fix it, but I haven't had the time to try it out yet.

```php
$options = ['headers' => $headers, 'body' => $body];
return $client->request($method, $uri, $options)->send();
```

**Comment by petarslavnic** [comment]
Try out a new release. Please, leave a feedback so I can close this issue.

**Comment by PsychicCat** [comment]
Ah yes good as new, thank you.
